avatars.avatar_service.settings.avatars_ak_common:tinygraphs_isogrids:
  type: avatars.avatar_service_common_base

avatars.avatar_service.settings.avatars_ak_common:tinygraphs_square:
  type: avatars.avatar_service_common_base

